"""Whole-history-bound deletion occupancy addresses.

Each deletion history contributes one fingerprint of its complete descendant.
All radius-one descendant fingerprints are generated by a one-step rolling
recurrence; descendant strings are never materialized by the active builder.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Sequence


DEFAULT_FINGERPRINT_MODULUS = (1 << 61) - 1


@dataclass(frozen=True, slots=True)
class HistoryOccupancyView:
    name: str
    bucket_count: int
    base: int
    multiplier: int
    modulus: int = DEFAULT_FINGERPRINT_MODULUS

    def __post_init__(self) -> None:
        if not self.name:
            raise ValueError("history occupancy view name must not be empty")
        if self.bucket_count < 2:
            raise ValueError("bucket count must be at least two")
        if not 1 < self.base < self.modulus:
            raise ValueError("base must lie strictly between one and modulus")
        if not 0 < self.multiplier < self.modulus:
            raise ValueError("multiplier must lie strictly between zero and modulus")


@dataclass(frozen=True, slots=True)
class HistoryOccupancyBuild:
    cells: tuple[frozenset[int], ...]
    coupled_history_keys: tuple[tuple[int, ...], ...]
    source_length: int
    fingerprint_updates: int
    atom_reads: int

    @property
    def posting_entries(self) -> int:
        return len(frozenset(self.coupled_history_keys))

    @property
    def separable_posting_entries(self) -> int:
        return sum(len(cells) for cells in self.cells)


def _atom_values(
    symbols: Sequence[str],
    atom_codes: Mapping[str, int],
    modulus: int,
) -> tuple[int, ...]:
    try:
        return tuple(atom_codes[symbol] % modulus for symbol in symbols)
    except KeyError as error:
        raise ValueError("source contains an atom without a code") from error


def _cell(fingerprint: int, view: HistoryOccupancyView) -> int:
    mixed = fingerprint * view.multiplier % view.modulus
    return mixed * view.bucket_count // view.modulus


def sequence_fingerprint(
    symbols: Sequence[str],
    atom_codes: Mapping[str, int],
    view: HistoryOccupancyView,
) -> int:
    """Return one declared polynomial fingerprint of the complete sequence."""

    values = _atom_values(symbols, atom_codes, view.modulus)
    fingerprint = 0
    power = 1
    for value in values:
        fingerprint = (fingerprint + value * power) % view.modulus
        power = power * view.base % view.modulus
    return fingerprint


def sequence_fingerprint_key(
    symbols: Sequence[str],
    atom_codes: Mapping[str, int],
    views: Sequence[HistoryOccupancyView],
) -> tuple[int, ...]:
    if not views:
        raise ValueError("at least one history occupancy view is required")
    return tuple(
        _cell(sequence_fingerprint(symbols, atom_codes, view), view)
        for view in views
    )


def build_deletion_history_occupancy(
    symbols: Sequence[str],
    atom_codes: Mapping[str, int],
    views: Sequence[HistoryOccupancyView],
) -> HistoryOccupancyBuild:
    """Build radius-one descendant keys in ``O(n * len(views))`` work."""

    if not symbols:
        raise ValueError("deletion occupancy requires a nonempty source")
    if not views:
        raise ValueError("at least one history occupancy view is required")
    occupied_by_view = []
    cells_by_history: list[list[int]] = [[] for _ in symbols]
    for view in views:
        values = _atom_values(symbols, atom_codes, view.modulus)
        descendant = 0
        power = 1
        for value in values[1:]:
            descendant = (descendant + value * power) % view.modulus
            power = power * view.base % view.modulus

        occupied: set[int] = set()
        rolling_power = 1
        for history in range(len(values)):
            cell = _cell(descendant, view)
            occupied.add(cell)
            cells_by_history[history].append(cell)
            if history + 1 < len(values):
                descendant = (
                    descendant
                    + (values[history] - values[history + 1]) * rolling_power
                ) % view.modulus
                rolling_power = rolling_power * view.base % view.modulus
        occupied_by_view.append(frozenset(occupied))
    return HistoryOccupancyBuild(
        cells=tuple(occupied_by_view),
        coupled_history_keys=tuple(tuple(cells) for cells in cells_by_history),
        source_length=len(symbols),
        fingerprint_updates=len(views) * max(0, len(symbols) - 1),
        atom_reads=len(views) * len(symbols),
    )


def history_occupancy_accepts(
    occupied_cells: Sequence[frozenset[int]],
    keys: Sequence[int],
) -> bool:
    if len(occupied_cells) != len(keys):
        raise ValueError("history occupancy and key counts must agree")
    return all(
        key in cells
        for cells, key in zip(occupied_cells, keys, strict=True)
    )


def history_occupancy_overlaps(
    left_cells: Sequence[frozenset[int]],
    right_cells: Sequence[frozenset[int]],
) -> bool:
    if len(left_cells) != len(right_cells):
        raise ValueError("history occupancy counts must agree")
    return all(
        not left.isdisjoint(right)
        for left, right in zip(left_cells, right_cells, strict=True)
    )


def coupled_history_accepts(
    history_keys: frozenset[tuple[int, ...]],
    full_key: tuple[int, ...],
) -> bool:
    if history_keys and len(next(iter(history_keys))) != len(full_key):
        raise ValueError("coupled history and full-key widths must agree")
    return full_key in history_keys


def coupled_history_overlaps(
    left_keys: frozenset[tuple[int, ...]],
    right_keys: frozenset[tuple[int, ...]],
) -> bool:
    if left_keys and right_keys:
        if len(next(iter(left_keys))) != len(next(iter(right_keys))):
            raise ValueError("coupled history-key widths must agree")
    return not left_keys.isdisjoint(right_keys)


def contract_history_cells(
    fine_cells: frozenset[int],
    fine_bucket_count: int,
    coarse_bucket_count: int,
) -> frozenset[int]:
    """Contract a nested uniform cell tower without rebuilding fingerprints."""

    if coarse_bucket_count < 2 or fine_bucket_count % coarse_bucket_count:
        raise ValueError("coarse bucket count must divide the fine bucket count")
    ratio = fine_bucket_count // coarse_bucket_count
    if any(cell < 0 or cell >= fine_bucket_count for cell in fine_cells):
        raise ValueError("fine cell lies outside the declared address")
    return frozenset(cell // ratio for cell in fine_cells)


def contract_coupled_history_keys(
    fine_keys: frozenset[tuple[int, ...]],
    fine_bucket_counts: Sequence[int],
    coarse_bucket_counts: Sequence[int],
) -> frozenset[tuple[int, ...]]:
    """Contract every coordinate of a coupled history-key set."""

    if len(fine_bucket_counts) != len(coarse_bucket_counts):
        raise ValueError("fine and coarse coordinate counts must agree")
    ratios = []
    for fine, coarse in zip(
        fine_bucket_counts, coarse_bucket_counts, strict=True
    ):
        if coarse < 2 or fine % coarse:
            raise ValueError(
                "every coarse bucket count must divide its fine count"
            )
        ratios.append(fine // coarse)
    width = len(ratios)
    if any(len(key) != width for key in fine_keys):
        raise ValueError("history-key width does not match the scale declaration")
    if any(
        cell < 0 or cell >= fine_bucket_counts[index]
        for key in fine_keys
        for index, cell in enumerate(key)
    ):
        raise ValueError("fine key cell lies outside its declared address")
    return frozenset(
        tuple(cell // ratios[index] for index, cell in enumerate(key))
        for key in fine_keys
    )
